services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ./packages/server/.env
      - ./packages/frontend/.env
    environment:
      - NODE_ENV=production
      - RELEASE=local
      - PORT=8000
      - CORS_HOSTS=http://localhost:8000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/secrets-vault
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --quiet --tries=1 --spider http://app:8000/api/v1/health || exit 1',
        ]
      interval: 1s
      timeout: 2s
      retries: 15 
    profiles:
      - app
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  db:
    image: postgres:17.6-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 1s
      timeout: 2s
      retries: 15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: secrets-vault
    ports:
      - 5432:5432

  migrations:
    build:
      context: .
      dockerfile: migrations.Dockerfile
    profiles:
      - app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/secrets-vault
